FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=accwe-hospital
ENV MYSQL_USER=your_user
ENV MYSQL_PASSWORD=your_password

COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 3306

CMD ["mysqld"]
